# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

deg2rad <- function(deg) {
    .Call('Rvoterdistance_deg2rad', PACKAGE = 'Rvoterdistance', deg)
}

rad2deg <- function(rad) {
    .Call('Rvoterdistance_rad2deg', PACKAGE = 'Rvoterdistance', rad)
}

distanceEarth <- function(lat1d, lon1d, lat2d, lon2d) {
    .Call('Rvoterdistance_distanceEarth', PACKAGE = 'Rvoterdistance', lat1d, lon1d, lat2d, lon2d)
}

vecminInd <- function(x) {
    .Call('Rvoterdistance_vecminInd', PACKAGE = 'Rvoterdistance', x)
}

nearest_dbox <- function(lat1d_vec, lon1d_vec, lat2d_vec, lon2d_vec) {
    .Call('Rvoterdistance_nearest_dbox', PACKAGE = 'Rvoterdistance', lat1d_vec, lon1d_vec, lat2d_vec, lon2d_vec)
}

nearest_dbox2 <- function(lat_lon1d, lat_lon2d) {
    .Call('Rvoterdistance_nearest_dbox2', PACKAGE = 'Rvoterdistance', lat_lon1d, lat_lon2d)
}

